### ISSUE TITLE
cool models running: one, maybe two, product lines

### ISSUE THREAD

**Issue by timm** [ai-se/storm#8]
one of the german's bigger product lines might be cool

if you have time then, from On the Value of User Preferences in Search-Based Software Engineering: A Case Study in Software Product Lines Abdel Salam Sayyad Tim Menzies Hany Ammar i see that web portal looks not too evil and eshop might be beyond the oct/nov task. but i can't find "web portal" at

http://splot-research.org/ > "Feature Model Repostiroy" > "Feature Model Repository". i'll ask abdel. but maybe you should ust use the german one

![image](https://cloud.githubusercontent.com/assets/29195/10199233/be44742c-676d-11e5-8bfb-a8b0389049d9.png)

**Comment by timm** [comment]
Abdel reports that it is called Web_Portal.

**Comment by vivekaxl** [comment]
@Ginfung This is related to objective1: do I even care about the number of features, if the product is just not feasible?

**Comment by ginfung** [comment]
That's another story. when the product is not feasible, it may:
1) if no constraint can be violated->obj1 is useless;
2) if constraint violation is also one consideration-> obj1 is useful (try to find the solution with more features and less constraint violation).

**Comment by vivekaxl** [comment]
@timm What do you think?
Context: @Ginfung's model for SPL has a objective which counts how many features have been obtained (without considering if the product is feasible). I am using the 3 objective model (# of features satisfied, # constraints, cost).
@Ginfung Correct me if I am wrong.

**Comment by ginfung** [comment]
there're bunches of algorithm to detect whether one model is feasible and they are very efficient. I don't think we should focus on it. @vivekaxl your idea?

**Comment by vivekaxl** [comment]
well there a couple of things I am thinking of (conflicting)
- if you use your current version of the program, you don't need to use continuous domination, since you are scoring solutions in a finer granularity (this is great)
- in CPM work, what I did was a very simple thing...if the product is not feasible return 1e32 (problem was a minimization problem) sidenote: continuous domination worked well in this case
- This is how I see this problem, I have a bunch of valid solutions and as a customer I need to choose one of these solutions. What use do I have looking at invalid solutions?
  I feel that your code is correct and I am just wondering it might have further implications (which I am not sure of).
  That being is said..do you see valid solutions in your final generation?

**Comment by vivekaxl** [comment]
JianFeng code has been integrated.
